 
# RMF Megazo door parameters

### template ###
doors:
  "Lab_D01":  # door name and id. Ensure that it mirrors its name on evcard platform and RMF map.
    door_auto_closes: False # Set to True if door remains closed until requested open, and automatically closes if it does not receive subsequent open requests.
    door_signal_period: 10.0 # Time taken for door signal to be effective, in seconds.
    continuous_status_polling: False # Whether to keep checking door state when there are no requests
    enable_mqtt_status_polling: False # Whether to use MQTT method of polling as alternative to ICEDList status polling.

door_subscriber:
  request_topic_name: "adapter_door_requests"
  mqtt_topic_name: "mqtt_door_status"


door_publisher:
  topic_name: "door_states"
  door_state_publish_period: 1.0 # Seconds

mock: False

# Sample creds:
api_endpoint: "https://www.evcard.cc:8181"
mqtt_broker: "icad.megazo.io"
mqtt_port: 1883
header_key: "INSERT MEGAZO USER HERE"
header_value: "INSERT MEGAZO PASSWORD HERE"
